joint_ids_map: [3,4,5,0,1,2,9,10,11,6,7,8]
step_dt: 0.02
stiffness: [100, 100, 150, 100, 100, 150, 100, 100, 150, 100, 100, 150]
damping:   [  4,   4,   6,   4,   4,   6,   4,   4,   6,   4,   4,   6]
default_joint_pos: [-0.1,0.9,-1.8, 0.1,0.9,-1.8, -0.1,0.9,-1.8, 0.1,0.9,-1.8]

commands:
  base_velocity:
    ranges:
      lin_vel_x: [-1.0, 2.0]
      lin_vel_y: [-1.0, 1.0]
      ang_vel_z: [-1.0, 1.0]
      heading: null
actions:
  JointPositionAction:
    clip: null
    joint_names: [.*]
    scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
    offset: [-0.1,0.9,-1.8, 0.1,0.9,-1.8, -0.1,0.9,-1.8, 0.1,0.9,-1.8]
    joint_ids: null
observations:
  base_ang_vel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  projected_gravity:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  velocity_commands:
    params: { command_name: base_velocity }
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  gait_phase:
    params: {period: 0.6}
    clip: null
    scale: [1.0, 1.0]
    history_length: 1
  joint_pos_rel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  joint_vel_rel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  last_action:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
